ALTER TABLE penas ADD COLUMN IF NOT EXISTS consumo_cerveza REAL DEFAULT 1.0;
ALTER TABLE penas ADD COLUMN IF NOT EXISTS consumo_tinto REAL DEFAULT 0.375;
ALTER TABLE penas ADD COLUMN IF NOT EXISTS consumo_cubata REAL DEFAULT 0.35;
ALTER TABLE penas ADD COLUMN IF NOT EXISTS consumo_refresco REAL DEFAULT 1.5;
ALTER TABLE penas ADD COLUMN IF NOT EXISTS consumo_agua REAL DEFAULT 1.0;
ALTER TABLE penas ADD COLUMN IF NOT EXISTS consumo_hielo REAL DEFAULT 0.5;
